# States

S_START  = 'START'  # default value
S_NEWEST = 'NEWEST'
S_RANDOM = 'RANDOM'
S_NUMBER = 'NUMBER'
S_PHRASE = 'PHRASE'

STATES   = [ S_START, S_NEWEST, S_RANDOM, S_NUMBER, S_PHRASE ]

S_OLDEST = 'OLDEST'
S_NEXT   = 'NEXT'
S_PREV   = 'PREV'